version: "3.0"

services:

  mongo:
    container_name: mongo
    image: centos/mongodb-32-centos7
    env_file:  
      - .env
    ports: 
      - "27017:27017" 
    volumes: 
      - "./docker/volumes/db/data:/var/lib/mongodb/data" 

  app:
    container_name: appnode
    image: ven4media
    build: 
        context: .
    ports:
        - "3000:3000"
    volumes: 
     - "./docker/volumes/app/upload:/home/app/src/public/upload"
    depends_on:
        - mongo